/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b6f5b384-3739-4fe0-acea-4af5b2ae78ff",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_hKkwJCB4O",
    "aws_user_pools_web_client_id": "261umf5hes1q3lug2aait6vqaf",
    "oauth": {},
    "aws_user_files_s3_bucket": "aerospec-dashboard-user-data-storage160954-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ocunbow4obe43b2awvwv6c7v7a.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h7p5p7h73fhujicb7q4vifvqli"
};


export default awsmobile;
